### PR TITLE
Update Illuminate packages to the 5.0 release

### PR DESCRIPTION
**Pull request by jwcobb**

### CODE REVIEW

**Comment by PatrickRose** [comment]
Doesn't that disallow 4.2? I'm not dropping 4.2 support.

**Comment by jwcobb** [comment]
Good point. 0d24834 Should allow for both 4.2 and 5.0

**Comment by PatrickRose** [comment]
Life would've been so much easier if Taylor had just added `package()` back in. I've just booted up a laravel 5 and this won't work just yet.

Thanks for the PR though!

**Comment by PatrickRose** [comment]
See #266

**Comment by PatrickRose** [comment]
Latest commit has these changes, closing

**Pull request closed without merging**
