### PR TITLE
Add support for custom column labels

### PR DESCRIPTION
**Pull request by anyguy**
Just find out about Bootstrapper today, nice work.

I couldn't find a quick way to override the labels of the header when using Eloquent models, so I added it.

Hopefully it's ok

### CODE REVIEW

**Comment by PatrickRose** [comment]
I might be misunderstanding - doesn't the TableInterface provide this?

**Comment by anyguy** [comment]
Let's say I have a Posts model with:

```php
   public function getTableHeaders()
    {
    	return ['name', 'is_draft'];
    }

    public function getValueForHeader($header)
    {
    	return $this->{$header};
    }
```

Then I will get this table:

name | is_draft
------------ | -------------
Post 1 | Yes
Post 2 | No

but instead I want to get:

Title | Draft
------------ | -------------
Post 1 | Yes
Post 2 | No

the difference being just in the column headings.

To obtain this, I would set `$table->withLabels(['name' => 'Title', 'is_draft' => 'Draft'])`

Is there already a way to get this without this patch?

Thanks!

**Comment by PatrickRose** [comment]
You could change it to this?

```php
   public function getTableHeaders()
    {
        return ['Title', 'Draft'];
    }

    public function getValueForHeader($header)
    {
        switch ($header) 
        {
            case 'Title':
                return $this->name;
            case 'Draft':
                return $this->is_draft;
    }
```

**Comment by anyguy** [comment]
ok great, thanks, now I see it

I didn't think about that because at first sight I though about the getValueForHeader() function only as a way to apply some formatting to the values if needed.

Now I got it  :-)

**Pull request closed without merging**
