### PR TITLE
Changed ->getToken() to ->token() for Laravel 5.4

### PR DESCRIPTION
**Pull request by RalphMRivera**

### CODE REVIEW

**Comment by tortuetorche** [comment]
Hi @RalphMRivera,

To keep backwards compatibility, you should update your pull request like this (:warning: untested code):
```php
(method_exists($app['session.store'], 'getToken') ? $app['session.store']->getToken() : $app['session.store']->token()),
```

Have a good day,
Tortue Torche

**Comment by RalphMRivera** [comment]
Added. Thanks for the feedback!

**Comment by PatrickRose** [comment]
Unit tests are failing as well - could you update them?

I'm also in the process of moving Bootstrapper to a separate repo and make these sort of things much less of a pain to handle. I've been trying to do this for 12 months though so...

**Comment by lloy0076** [comment]
@RalphMRivera  / @PatrickRose  - What's wrong with the csrf_token() helper?

Like this:

```
195     private function registerFormBuilder()
196     {
197         $this->app->bind(
198             'collective::html',
199             function ($app) {
200                 return new HtmlBuilder($app->make('url'), $app->make('view'));
201             }
202         );
203         $this->app->bind(
204             'bootstrapper::form',
205             function ($app) {
206                 $form = new Form(
207                     $app->make('collective::html'),
208                     $app->make('url'),
209                     $app->make('view'),
210                     //$app['session.store']->getToken()
211                     csrf_token()
212                 );
213
214                 return $form->setSessionStore($app['session.store']);
215             },
216             true
217         );
218     }
```

This seems to exist in Laravel 5.0 (see https://laravel.com/docs/5.0/helpers).

I'm not sure about Laravel 4.X (or lower) but this **is** the 5.X support.

**Comment by tortuetorche** [comment]
Hi @RalphMRivera,

I think you need to update this file in your pull request, to pass tests:
https://github.com/patricktalmadge/bootstrapper/blob/4180ddf4bb889ed731478a07fcca3492884eb4c2/tests/spec/Bootstrapper/BootstrapperL5ServiceProviderSpec.php#L98

Cheers,
Tortue Torche

**Comment by tortuetorche** [comment]
Hi @RalphMRivera,

If you merge my pull request https://github.com/RalphMRivera/bootstrapper/issues/1, the unit tests will be OK.
Then, I think, @PatrickRose will merge your pull request.

Have a good day,
Tortue Torche

**Comment by tortuetorche** [comment]
This pull request could be closed, see #321

**Pull request closed without merging**
