### PR TITLE
added ability to set HTML icon tag

### PR DESCRIPTION
**Pull request by pjona**
So you can generate icons with `<i>` tag.

### CODE REVIEW

**Comment by PatrickRose** [comment]
What's your use case here? Semantically it should be a span not an I?

**Comment by pjona** [comment]
So my use case is to generate icons with `<i>` tag instant of `<span>` because in my project `<span>` has already another CSS styles. I also make research and the are opinions differ. For example still few big icon providers uses the `<i>`: [Font Awesome](http://fontawesome.io/icon/address-book-o/), [Google Icons](https://material.io/icons) so I think is good to give the opportunity to the user, which one he wants to use.

**Comment by pjona** [comment]
PatrickRose: You plan to merge it? It not breaks anything and has test :)

**Comment by PatrickRose** [comment]
Will do a release later this week

**Pull request merged**
